/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.bartgui.view.panel.editor.database.visual;

/**
 *
 * @author Grandinetti Giovanni <grandinetti.giovanni13@gmail.com>
 */
public class PaginationCtrlPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaginationCtrlPanel
     */
    public PaginationCtrlPanel() {
        initComponents();
    }
    
    public void setNumOfPages(String s)   {
        numerOfPageTextField.setText(s);
    }
    
    public void setPageSize(String s)   {
        pageSizeTextField.setText(s);
    }
    
    public String getPageSize()   {
        return pageSizeTextField.getText();
    }
    
    public void setVisibleRow(String s)   {
        visibleRowTextField.setText(s);
    }
    
    public String getVisibleRow()   {
        return visibleRowTextField.getText();
    }
    
    public void setSelectedPage(String s)   {
        selectedPageTextField.setText(s);
    }
    
    public String getSelectedPage()   {
        return selectedPageTextField.getText();
    }
    
    public void setTableSize(String s)   {
        tableSizeTextField.setText(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pageSizeTextField = new javax.swing.JTextField();
        visibleRowTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numerOfPageTextField = new javax.swing.JTextField();
        selectedPageTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tableSizeTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        firstButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(62, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(62, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(62, 14));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.jLabel2.text")); // NOI18N

        pageSizeTextField.setText(org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.pageSizeTextField.text")); // NOI18N
        pageSizeTextField.setMaximumSize(new java.awt.Dimension(100, 25));
        pageSizeTextField.setMinimumSize(new java.awt.Dimension(40, 25));
        pageSizeTextField.setPreferredSize(new java.awt.Dimension(40, 25));

        visibleRowTextField.setText(org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.visibleRowTextField.text")); // NOI18N
        visibleRowTextField.setMaximumSize(new java.awt.Dimension(100, 25));
        visibleRowTextField.setMinimumSize(new java.awt.Dimension(40, 25));
        visibleRowTextField.setPreferredSize(new java.awt.Dimension(40, 25));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.jLabel3.text")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(78, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(78, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(78, 14));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.jLabel4.text")); // NOI18N

        numerOfPageTextField.setEditable(false);
        numerOfPageTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numerOfPageTextField.setForeground(new java.awt.Color(0, 0, 204));
        numerOfPageTextField.setText(org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.numerOfPageTextField.text")); // NOI18N
        numerOfPageTextField.setMaximumSize(new java.awt.Dimension(100, 25));
        numerOfPageTextField.setMinimumSize(new java.awt.Dimension(40, 25));
        numerOfPageTextField.setPreferredSize(new java.awt.Dimension(40, 25));

        selectedPageTextField.setText(org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.selectedPageTextField.text")); // NOI18N
        selectedPageTextField.setMaximumSize(new java.awt.Dimension(100, 25));
        selectedPageTextField.setMinimumSize(new java.awt.Dimension(40, 25));
        selectedPageTextField.setPreferredSize(new java.awt.Dimension(40, 25));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.jLabel8.text")); // NOI18N

        tableSizeTextField.setEditable(false);
        tableSizeTextField.setBackground(new java.awt.Color(255, 255, 255));
        tableSizeTextField.setText(org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.tableSizeTextField.text")); // NOI18N

        firstButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unibas/bartgui/view/panel/editor/database/visual/icon/first.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(firstButton, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.firstButton.text")); // NOI18N

        prevButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unibas/bartgui/view/panel/editor/database/visual/icon/prev.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(prevButton, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.prevButton.text")); // NOI18N

        lastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unibas/bartgui/view/panel/editor/database/visual/icon/last.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lastButton, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.lastButton.text")); // NOI18N

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unibas/bartgui/view/panel/editor/database/visual/icon/next.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(nextButton, org.openide.util.NbBundle.getMessage(PaginationCtrlPanel.class, "PaginationCtrlPanel.nextButton.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstButton)
                .addGap(18, 18, 18)
                .addComponent(prevButton)
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addGap(18, 18, 18)
                .addComponent(lastButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(firstButton)
                .addComponent(prevButton)
                .addComponent(lastButton)
                .addComponent(nextButton))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numerOfPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pageSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(visibleRowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(visibleRowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator4)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numerOfPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(selectedPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pageSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tableSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField numerOfPageTextField;
    private javax.swing.JTextField pageSizeTextField;
    private javax.swing.JButton prevButton;
    private javax.swing.JTextField selectedPageTextField;
    private javax.swing.JTextField tableSizeTextField;
    private javax.swing.JTextField visibleRowTextField;
    // End of variables declaration//GEN-END:variables



    /**
     * @return the firstButton
     */
    public javax.swing.JButton getFirstButton() {
        return firstButton;
    }



    /**
     * @return the lastButton
     */
    public javax.swing.JButton getLastButton() {
        return lastButton;
    }

    /**
     * @return the nextButton
     */
    public javax.swing.JButton getNextButton() {
        return nextButton;
    }

    /**
     * @return the numerOfPageTextField
     */
    public javax.swing.JTextField getNumerOfPageTextField() {
        return numerOfPageTextField;
    }

    /**
     * @return the pageSizeTextField
     */
    public javax.swing.JTextField getPageSizeTextField() {
        return pageSizeTextField;
    }

    /**
     * @return the prevButton
     */
    public javax.swing.JButton getPrevButton() {
        return prevButton;
    }

    /**
     * @return the selectedPageTextField
     */
    public javax.swing.JTextField getSelectedPageTextField() {
        return selectedPageTextField;
    }

    /**
     * @return the visibleRowTextField
     */
    public javax.swing.JTextField getVisibleRowTextField() {
        return visibleRowTextField;
    }
}
