/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.bartgui.view.topComponent;

import it.unibas.bartgui.resources.R;
import it.unibas.bartgui.view.ViewResource;
import it.unibas.centrallookup.CentralLookup;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ActionMap;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//it.unibas.bartgui.view.topComponent//StatExecutions//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "StatExecutionsTopComponent",
        iconBase=R.IMAGE_STATISTIC, 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "navigator", openAtStartup = true)
@ActionID(category = "Window", id = "it.unibas.bartgui.view.topComponent.StatExecutionsTopComponent")
@ActionReference(path = "Menu/Window" , position = 30)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_StatExecutionsAction",
        preferredID = ViewResource.TOP_ID_StatExecutionsTopComponent
)
@Messages({
    "CTL_StatExecutionsAction=Statistics Results",
    "CTL_StatExecutionsTopComponent=Statistics Executions Window",
    "HINT_StatExecutionsTopComponent=This is a StatExecutions window"
})
public final class StatExecutionsTopComponent extends TopComponent implements ExplorerManager.Provider,LookupListener  {

    private transient ExplorerManager exm = new ExplorerManager();
    private Lookup.Result<Node> result;
    
    public StatExecutionsTopComponent() {
        initComponents();
        setDisplayName(Bundle.CTL_StatExecutionsTopComponent());
        setName(ViewResource.TOP_NAME_StatExecutionsTopComponent);
        setToolTipText(Bundle.HINT_StatExecutionsTopComponent());
        setBackground(Color.WHITE);
        setLayout(new BorderLayout());
        add(new BeanTreeView(),BorderLayout.CENTER);
        ActionMap  map = this.getActionMap();
        map.put("delete", ExplorerUtils.actionDelete(exm, true));
        associateLookup(ExplorerUtils.createLookup(exm, this.getActionMap()));
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return exm;
    }

    @Override
    public void resultChanged(LookupEvent ev) {
        Node n = CentralLookup.getDefLookup().lookup(Node.class);
        if(n == null)   {
            exm.setRootContext(new AbstractNode(Children.LEAF));
        }else{
            exm.setRootContext(n);
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        result = CentralLookup.getDefLookup().lookupResult(Node.class);
        result.addLookupListener(this);
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
