/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.bartgui.view.panel.editor.autoritativesrc;

import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Grandinetti Giovanni <grandinetti.giovanni13@gmail.com>
 */
@SuppressWarnings({"unchecked","rawtypes"})
public class AutoritativeSrcPanel extends javax.swing.JPanel {

    private javax.swing.JButton CancelButton;
    private javax.swing.JButton OkButton;
    /**
     * Creates new form autoritativeSrcPanel
     */
    public AutoritativeSrcPanel() {
        initComponents();
        initCombo();
        initButtons();
    }
    
    private void initCombo()   {
        jComboBox1.setEditable(false);
        //jComboBox1.setAction(null);
        jComboBox1.setActionCommand("itemSelected");
    }
    
    private void initButtons()   {
        OkButton = new JButton("OK");
        OkButton.setActionCommand("OK");
        CancelButton = new JButton("Cancel");;
        CancelButton.setActionCommand("Cancel");
        
    }
    
    public JButton[] getButtons()   {
        JButton b[] ={OkButton,CancelButton};
        return b;
    }

    public Object getSelectedItem()   {
        return jComboBox1.getSelectedItem();
    }
    
    public void setItem(List<String> items)   {
        for(String s : items)   {
            jComboBox1.addItem(s);
        }
        jComboBox1.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AutoritativeSrcPanel.class, "AutoritativeSrcPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AutoritativeSrcPanel.class, "AutoritativeSrcPanel.jLabel2.text")); // NOI18N

        jComboBox1.setToolTipText(org.openide.util.NbBundle.getMessage(AutoritativeSrcPanel.class, "AutoritativeSrcPanel.jComboBox1.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
