/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.bartgui.view.panel.editor.database;

/**
 *
 * @author Grandinetti Giovanni <grandinetti.giovanni13@gmail.com>
 */
public class AccesConfPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccesConfPanel
     */
    public AccesConfPanel() {
        initComponents();
        initName();
    }

    private void initName()   {
        getDriverTextField().setName("Driver");
        getUriTextField().setName("URI");
        getSchemaTextField().setName("Schema");
        getLoginTextField().setName("Login");
        getPasswordTextField().setName("Password");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        driverTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        uriTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        schemaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.jLabel1.text")); // NOI18N

        driverTextField.setText(org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.driverTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.jLabel2.text")); // NOI18N

        uriTextField.setText(org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.uriTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.jLabel3.text")); // NOI18N

        schemaTextField.setText(org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.schemaTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.jLabel4.text")); // NOI18N

        loginTextField.setText(org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.loginTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.jLabel5.text")); // NOI18N

        passwordTextField.setText(org.openide.util.NbBundle.getMessage(AccesConfPanel.class, "AccesConfPanel.passwordTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uriTextField)
                    .addComponent(schemaTextField)
                    .addComponent(loginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(passwordTextField)
                    .addComponent(driverTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(driverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(uriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(schemaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField driverTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField schemaTextField;
    private javax.swing.JTextField uriTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the driverTextField
     */
    public javax.swing.JTextField getDriverTextField() {
        return driverTextField;
    }

    /**
     * @return the loginTextField
     */
    public javax.swing.JTextField getLoginTextField() {
        return loginTextField;
    }

    /**
     * @return the passwordTextField
     */
    public javax.swing.JTextField getPasswordTextField() {
        return passwordTextField;
    }

    /**
     * @return the schemaTextField
     */
    public javax.swing.JTextField getSchemaTextField() {
        return schemaTextField;
    }

    /**
     * @return the uriTextField
     */
    public javax.swing.JTextField getUriTextField() {
        return uriTextField;
    }
}
