/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.bartgui.view.panel.editor.database;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTextArea;

/**
 *
 * @author Grandinetti Giovanni <grandinetti.giovanni13@gmail.com>
 */
public class InitDBPanel extends javax.swing.JPanel {

    private JTextArea scriptArea ;
    /**
     * Creates new form InitDBPanel
     */
    public InitDBPanel() {
        initComponents();
        scriptArea = new JTextArea();
        init();
        initListener();
    }

    private void init()  {
        scriptArea.setName("Init DB Script AREA");
        scriptArea.setLineWrap(false);
        scriptArea.setEditable(false);
        initScriptScrollPane1.setViewportView(scriptArea);
        scriptArea.setEnabled(false);
        initDbCheckBox.setSelected(false);
        initScriptScrollPane1.setEnabled(false);              
    }
    
    private void initListener()   {
        initDbCheckBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(initDbCheckBox.isSelected())   {
                    initScriptScrollPane1.setEnabled(true);
                    scriptArea.setEnabled(true);
                    scriptArea.setEditable(true);                                     
                }else{
                    scriptArea.setEditable(false);
                    scriptArea.setEnabled(false);
                    initScriptScrollPane1.setEnabled(false);
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initDbCheckBox = new javax.swing.JCheckBox();
        initScriptScrollPane1 = new javax.swing.JScrollPane();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(InitDBPanel.class, "InitDBPanel.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(initDbCheckBox, org.openide.util.NbBundle.getMessage(InitDBPanel.class, "InitDBPanel.initDbCheckBox.text")); // NOI18N
        initDbCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        initScriptScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(InitDBPanel.class, "InitDBPanel.initScriptScrollPane1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 204))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initDbCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(initScriptScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(initDbCheckBox)
                    .addComponent(initScriptScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox initDbCheckBox;
    private javax.swing.JScrollPane initScriptScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the initDbCheckBox
     */
    public javax.swing.JCheckBox getInitDbCheckBox() {
        return initDbCheckBox;
    }

    /**
     * @return the initScriptScrollPane1
     */
    public javax.swing.JScrollPane getInitScriptScrollPane1() {
        return initScriptScrollPane1;
    }

    /**
     * @return the scriptArea
     */
    public JTextArea getScriptArea() {
        return scriptArea;
    }
}
