/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.bartgui.view.panel.editor.database;

import javax.swing.ButtonGroup;

/**
 *
 * @author Grandinetti Giovanni <grandinetti.giovanni13@gmail.com>
 */
public class SeletcTypeDBPanel extends javax.swing.JPanel {

    private ButtonGroup group;
    /**
     * Creates new form SeletcTypeDBPanel
     */
    public SeletcTypeDBPanel() {
        initComponents();
        initGroup();
    }
    
    private void initGroup()   {
        group = new ButtonGroup();
        group.add(dbmsdbRadioButton);
        group.add(mainMemoryRadioButton);
        group.add(mainMemGenerateRadioButton);
        dbmsdbRadioButton.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbmsdbRadioButton = new javax.swing.JRadioButton();
        mainMemoryRadioButton = new javax.swing.JRadioButton();
        mainMemGenerateRadioButton = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(SeletcTypeDBPanel.class, "SeletcTypeDBPanel.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dbmsdbRadioButton, org.openide.util.NbBundle.getMessage(SeletcTypeDBPanel.class, "SeletcTypeDBPanel.dbmsdbRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(mainMemoryRadioButton, org.openide.util.NbBundle.getMessage(SeletcTypeDBPanel.class, "SeletcTypeDBPanel.mainMemoryRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(mainMemGenerateRadioButton, org.openide.util.NbBundle.getMessage(SeletcTypeDBPanel.class, "SeletcTypeDBPanel.mainMemGenerateRadioButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbmsdbRadioButton)
                .addGap(18, 18, 18)
                .addComponent(mainMemoryRadioButton)
                .addGap(18, 18, 18)
                .addComponent(mainMemGenerateRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbmsdbRadioButton)
                    .addComponent(mainMemoryRadioButton)
                    .addComponent(mainMemGenerateRadioButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton dbmsdbRadioButton;
    private javax.swing.JRadioButton mainMemGenerateRadioButton;
    private javax.swing.JRadioButton mainMemoryRadioButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dbmsdbRadioButton
     */
    public javax.swing.JRadioButton getDbmsdbRadioButton() {
        return dbmsdbRadioButton;
    }

    /**
     * @return the mainMemGenerateRadioButton
     */
    public javax.swing.JRadioButton getMainMemGenerateRadioButton() {
        return mainMemGenerateRadioButton;
    }

    /**
     * @return the mainMemoryRadioButton
     */
    public javax.swing.JRadioButton getMainMemoryRadioButton() {
        return mainMemoryRadioButton;
    }
}
